<?php
define("TBL_ADMIN","admin_master");
define("TBL_USER","user_master");
define("TBL_REPORT","report_master");
define("TBL_SUMMARY","report_summary");
//define("TBL_OBT_GROUP","obt_group");
define("TBL_OBT_GROUP","obt_group");
//define("TBL_REPORT_CAT","report_category");
define("TBL_REPORT_CAT","report_category");
define("TBL_REPORT_SUBCAT","report_subcategory");
//define("TBL_REPORT_CODE","report_code");
define("TBL_REPORT_CODE","report_code");
define("TBL_DEVICE","apns_devices");
define("TBL_APNMESSAGE","apns_messages");
define("TBL_APNUSERMESSAGE","apns_user_messages");
?>